version: 0.2

phases:
  install:
    commands:
      - bash -c "$(curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install)"
      - printenv
  build:
    commands:
      - printenv
