apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello
    #  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-external: 0.0.0.0/0
spec:
  type: NodePort
#  clusterIP: 10.0.171.239
#  loadBalancerIP: 78.11.24.19
  ports:
  - port: 80
    protocol: TCP
    name: http
    #  - port: 443
    #protocol: TCP
    #name: https
  selector:
    app: hello
#  status:
#		loadBalancer:
#			ingress:
#			- ip: 146.148.47.155:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-web
        image: 212291129513.dkr.ecr.us-east-1.amazonaws.com/hello-web:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
#---
#apiVersion: v1
#kind: ReplicationController
#metadata:
#  name: hello-web
#spec:
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        app: hello
#    spec:
#      #      volumes:
#      #- name: secret-volume
#      #  secret:
#      #    secretName: nginxsecret
#      #- name: configmap-volume
#      #  configMap:
#      #    name: nginxconfigmap
#      containers:
#      - name: hello-web
#        image: 212291129513.dkr.ecr.us-east-1.amazonaws.com/hello-web:latest
#        #        command: ["/home/auto-reload-nginx.sh"]
#        ports:
#          #        - containerPort: 443
#        - containerPort: 80
#        livenessProbe:
#          httpGet:
#            path: /index.html
#            port: 80
#          initialDelaySeconds: 30
#          timeoutSeconds: 1
#          #        volumeMounts:
#          #        - mountPath: /etc/nginx/ssl
#          #          name: secret-volume
#          #        - mountPath: /etc/nginx/conf.d
#          #          name: configmap-volume
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-hello-ingress
  #  annotations:
    #    ingress.kubernetes.io/rewrite-target: /
    #    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    #nginx.ingress.kubernetes.io/cors-allow-headers: Authorization, origin, accept
    #nginx.ingress.kubernetes.io/cors-allow-methods: GET, OPTIONS
    #nginx.ingress.kubernetes.io/cors-allow-origin: jenkins.dev.sc-cloud.net/web
    #nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
    backend:
     serviceName: hello-svc
     servicePort: 80
#  rules:
#  - host: stex-poc.dev.sc-cloud.net
#    http:
#      paths:
#      - path: /foo
#        backend:
#          serviceName: nginxsvc
#          servicePort: 80
#      - path: /bar
#        backend:
#          serviceName: nginxsvc
#          servicePort: 443
#
